import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth, signInWithPopup, GoogleAuthProvider, onAuthStateChanged, signOut, User } from 'firebase/auth';
import firebaseConfig from './firebase-applet-config.json';
const app = getApps().length > 0 ? getApp() : initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const DRIVE_SCOPES = ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.file', 'https://www.googleapis.com/auth/drive.readonly', 'https://www.googleapis.com/auth/drive.metadata.readonly'];
const provider = new GoogleAuthProvider();
DRIVE_SCOPES.forEach((scope) => provider.addScope(scope));
let cachedAccessToken: string | null = null;
export const initAuth = (onAuthSuccess?: (user: User, token: string) => void, onAuthFailure?: () => void) => onAuthStateChanged(auth, (user) => user && cachedAccessToken ? onAuthSuccess?.(user, cachedAccessToken) : onAuthFailure?.());
export const googleSignIn = async () => { const result = await signInWithPopup(auth, provider); const credential = GoogleAuthProvider.credentialFromResult(result); if (!credential?.accessToken) throw new Error('Falha ao obter token de acesso Google OAuth do Firebase Auth'); cachedAccessToken = credential.accessToken; return { user: result.user, accessToken: cachedAccessToken }; };
export const getAccessToken = async () => cachedAccessToken;
export const setAccessToken = (token: string | null) => { cachedAccessToken = token; };
export const logout = async () => { await signOut(auth); cachedAccessToken = null; };
