import { Contact } from '../types/inov';

export const INITIAL_CONTACTS: Contact[] = [
  // Imigrantes (Ecovias)
  {
    id: "GCC0001",
    concession: "Imigrantes",
    area: "GEN",
    function: "Ponto Focal",
    name: "Bruna Silva de Andrade",
    email: "Bruna.S.Andrade@ecovias.com.br",
    manager: "Wagner da Silva",
    observation: "Convênio PMRV",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0002",
    concession: "Imigrantes",
    area: "GEN",
    function: "Integrante",
    name: "Wagner da Silva",
    email: "Wagner.Silva@ecovias.com.br",
    manager: "Wagner da Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0003",
    concession: "Imigrantes",
    area: "GEN",
    function: "Integrante",
    name: "Renan Gomes Magrino",
    email: "renan.magrino@ecovias.com.br",
    manager: "Wagner da Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0004",
    concession: "Imigrantes",
    area: "GEN",
    function: "Integrante",
    name: "Thiago M. Santos",
    email: "thiago.m.santos@ecovias.com.br",
    manager: "Bruna Silva de Andrade",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0005",
    concession: "Imigrantes",
    area: "GAU",
    function: "Ponto Focal",
    name: "Daniele Rolim",
    email: "Daniele.Rolim@ecovias.com.br",
    manager: "Ghislaine Lury Testoni",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0006",
    concession: "Imigrantes",
    area: "GAU",
    function: "Grupo de E-mail",
    name: "Correspondências GAU",
    email: "correspondenciasgau@ecovias.com.br",
    manager: "Ghislaine Lury Testoni",
    observation: "Caixa compartilhada",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0007",
    concession: "Imigrantes",
    area: "GAU",
    function: "Integrante",
    name: "Gabriel Encarnação",
    email: "gabriel.encarnacao@ecovias.com.br",
    manager: "Ghislaine Lury Testoni",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0008",
    concession: "Imigrantes",
    area: "CSU",
    function: "Ponto Focal",
    name: "T_Luana Ferreira Vieira",
    email: "T_Luana.Vieira@ecovias.com.br",
    manager: "Alice Maria Costa Maia Silveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Sonda IT Serviços",
    tempoContrato: "10 meses restantes (Vence 07/2027)",
    atividadesDescricao: "Atendimento de Ouvidoria, triagem de chamados e suporte SAC rodoviário"
  },
  {
    id: "GCC0009",
    concession: "Imigrantes",
    area: "CSU",
    function: "Integrante",
    name: "Luan Vinicius do Nascimento Colucci",
    email: "Luan.Colucci@ecovias.com.br",
    manager: "Alice Maria Costa Maia Silveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0010",
    concession: "Imigrantes",
    area: "CSU",
    function: "Integrante",
    name: "Jefferson Cleber da Silva Junior",
    email: "jefferson.junior@ecovias.com.br",
    manager: "Alice Maria Costa Maia Silveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0011",
    concession: "Imigrantes",
    area: "CSU",
    function: "Integrante",
    name: "Alice Maria Costa Maia Silveira",
    email: "alice.maia@ecovias.com.br",
    manager: "Alice Maria Costa Maia Silveira",
    observation: "Gestor CSU",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0012",
    concession: "Imigrantes",
    area: "RH",
    function: "Ponto Focal",
    name: "Marcela Lima Barbery",
    email: "marcela.barbery@ecovias.com.br",
    manager: "Rafael Souza da Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0013",
    concession: "Imigrantes",
    area: "RH",
    function: "Integrante",
    name: "Rafael Souza da Silva",
    email: "rafael.silva@ecovias.com.br",
    manager: "Rafael Souza da Silva",
    observation: "Gestor da Área",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0014",
    concession: "Imigrantes",
    area: "AJL",
    function: "Ponto Focal",
    name: "Vinicius da Silva Faria",
    email: "vinicius.faria@ecovias.com.br",
    manager: "Julianna de Freitas Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0015",
    concession: "Imigrantes",
    area: "AJL",
    function: "Integrante",
    name: "Nayara das Merces Oliveira",
    email: "nayara.oliveira@ecovias.com.br",
    manager: "Julianna de Freitas Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0016",
    concession: "Imigrantes",
    area: "AJL",
    function: "Integrante",
    name: "Laine Barros Xavier",
    email: "laine.xavier@ecovias.com.br",
    manager: "Julianna de Freitas Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0017",
    concession: "Imigrantes",
    area: "AJL",
    function: "Integrante",
    name: "Marcela Cioccia Neves",
    email: "marcela.neves@ecovias.com.br",
    manager: "Julianna de Freitas Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0018",
    concession: "Imigrantes",
    area: "AJL",
    function: "Grupo de E-mail",
    name: "Jurídico EVI/EVLP",
    email: "juridico.evi.evlp@ecovias.com.br",
    manager: "Julianna de Freitas Silva",
    observation: "Caixa compartilhada",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0019",
    concession: "Imigrantes",
    area: "DTC",
    function: "Ponto Focal",
    name: "Milene Feriani",
    email: "milene.feriani@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0020",
    concession: "Imigrantes",
    area: "DTC",
    function: "Integrante",
    name: "João Paulos da Silva",
    email: "joao.silva@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0021",
    concession: "Imigrantes",
    area: "DTC",
    function: "Integrante",
    name: "Daniel Cirilo",
    email: "daniel.cirilo@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0022",
    concession: "Imigrantes",
    area: "DTC",
    function: "Integrante",
    name: "William Hartwig",
    email: "william.hartwig@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },

  // Leste Paulista (Ecopistas)
  {
    id: "GCC0023",
    concession: "Leste Paulista",
    area: "GEN",
    function: "Ponto Focal",
    name: "Wagner da Silva",
    email: "Wagner.Silva@ecovias.com.br",
    manager: "Bruna Silva de Andrade",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0024",
    concession: "Leste Paulista",
    area: "GEN",
    function: "Especialista",
    name: "Lara Leandro Farias",
    email: "Lara.Farias@ecovias.com.br",
    manager: "Bruna Silva de Andrade",
    observation: "ARTESP - Pavimento",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0025",
    concession: "Leste Paulista",
    area: "GEN",
    function: "Integrante",
    name: "Bruna Silva de Andrade",
    email: "Bruna.S.Andrade@ecovias.com.br",
    manager: "Wagner da Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0026",
    concession: "Leste Paulista",
    area: "GEN",
    function: "Integrante",
    name: "Thiago M. Santos",
    email: "thiago.m.santos@ecovias.com.br",
    manager: "Bruna Silva de Andrade",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0027",
    concession: "Leste Paulista",
    area: "GAU",
    function: "Ponto Focal",
    name: "Daniele Rolim",
    email: "Daniele.Rolim@ecovias.com.br",
    manager: "Ghislaine Lury Testoni",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0028",
    concession: "Leste Paulista",
    area: "GAU",
    function: "Grupo de E-mail",
    name: "GAU Ecopistas",
    email: "gau.ecopistas@ecovias.com.br",
    manager: "Ghislaine Lury Testoni",
    observation: "Caixa compartilhada",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0029",
    concession: "Leste Paulista",
    area: "GAU",
    function: "Integrante",
    name: "Gabriel Encarnação",
    email: "gabriel.encarnacao@ecovias.com.br",
    manager: "Ghislaine Lury Testoni",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0030",
    concession: "Leste Paulista",
    area: "CSU",
    function: "Ponto Focal",
    name: "T_Luana Ferreira Vieira",
    email: "T_Luana.Vieira@ecovias.com.br",
    manager: "Alice Maria Costa Maia Silveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Sonda IT Serviços",
    tempoContrato: "10 meses restantes (Vence 07/2027)",
    atividadesDescricao: "Gestão de filas de atendimento ao usuário e triagem de ocorrências"
  },
  {
    id: "GCC0031",
    concession: "Leste Paulista",
    area: "CSU",
    function: "Integrante",
    name: "Luan Vinicius do Nascimento Colucci",
    email: "Luan.Colucci@ecovias.com.br",
    manager: "Alice Maria Costa Maia Silveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0032",
    concession: "Leste Paulista",
    area: "CSU",
    function: "Integrante",
    name: "Alice Maria Costa Maia Silveira",
    email: "alice.maia@ecovias.com.br",
    manager: "Alice Maria Costa Maia Silveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0033",
    concession: "Leste Paulista",
    area: "RH",
    function: "Ponto Focal",
    name: "Marcela Lima Barbery",
    email: "marcela.barbery@ecovias.com.br",
    manager: "Rafael Souza da Silva",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0034",
    concession: "Leste Paulista",
    area: "RH",
    function: "Integrante",
    name: "Rafael Souza da Silva",
    email: "rafael.silva@ecovias.com.br",
    manager: "Rafael Souza da Silva",
    observation: "Gestor da Área",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0035",
    concession: "Leste Paulista",
    area: "DTC",
    function: "Ponto Focal",
    name: "Maria Shirley",
    email: "maria.shirley@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0036",
    concession: "Leste Paulista",
    area: "DTC",
    function: "Integrante",
    name: "João Paulos da Silva",
    email: "joao.silva@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0037",
    concession: "Leste Paulista",
    area: "DTC",
    function: "Integrante",
    name: "Daniel Cirilo",
    email: "daniel.cirilo@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0038",
    concession: "Leste Paulista",
    area: "DTC",
    function: "Integrante",
    name: "William Hartwig",
    email: "william.hartwig@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },

  // Econoroeste
  {
    id: "GCC0039",
    concession: "Econoroeste",
    area: "GEN",
    function: "Ponto Focal",
    name: "Guilherme Ferreira dos Santos",
    email: "guilherme.santos@econoroeste.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0040",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Marcela de Paula",
    email: "marcela.paula@econoroeste.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0041",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Maria Eduarda Francischini da Silva",
    email: "maria.silva@econoroeste.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0042",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Lucas Fernando dos Santos",
    email: "lucas.santos@econoroeste.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0043",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Sofia Carvalho",
    email: "T_Sofia.Carvalho@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Consórcio Conserva SP",
    tempoContrato: "14 meses restantes (Vence 11/2027)",
    atividadesDescricao: "Fiscalização de conservação de pista e cadastro de ocorrências viárias"
  },
  {
    id: "GCC0044",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Giovana Rodrigues",
    email: "T_Giovana.Rodrigues@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Consórcio Conserva SP",
    tempoContrato: "8 meses restantes (Vence 05/2027)",
    atividadesDescricao: "Elaboração de relatórios fotográficos de conservação e vistorias de campo"
  },
  {
    id: "GCC0045",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Leire Souza",
    email: "T_Leire.Souza@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Engenharia & Soluções Viárias",
    tempoContrato: "6 meses restantes (Vence 03/2027)",
    atividadesDescricao: "Controle de medição de obras rodoviárias e apoio documental ARTESP"
  },
  {
    id: "GCC0046",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Caroline Placeres",
    email: "T_Caroline.Placeres@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Engenharia & Soluções Viárias",
    tempoContrato: "18 meses restantes (Vence 03/2028)",
    atividadesDescricao: "Vistoria de faixas de domínio e análise de interferências viárias"
  },
  {
    id: "GCC0047",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Mikaelly Marcelino",
    email: "T_Mikaelly.Marcelino@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "TechRoad Engenharia",
    tempoContrato: "12 meses restantes (Vence 09/2027)",
    atividadesDescricao: "Apoio em projetos de geometria e sinalização vertical e horizontal"
  },
  {
    id: "GCC0048",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Weverton Teixeira",
    email: "Weverton.Teixeira@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0049",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Samuel Ribeiro",
    email: "t_samuel.ribeiro@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "TechRoad Engenharia",
    tempoContrato: "12 meses restantes (Vence 09/2027)",
    atividadesDescricao: "Fiscalização de pavimento e ensaios de defletometria"
  },
  {
    id: "GCC0050",
    concession: "Econoroeste",
    area: "GEN",
    function: "Grupo de E-mail",
    name: "Faixa de Domínio",
    email: "faixadedominio@econoroeste.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0051",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Ana Durante",
    email: "T_Ana.Durante@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Consórcio Conserva SP",
    tempoContrato: "9 meses restantes (Vence 06/2027)",
    atividadesDescricao: "Controle de desapropriações e notificações de faixa de domínio"
  },
  {
    id: "GCC0052",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Osmar Jacinto Nogueira Junior",
    email: "osmar.nogueira@econoroeste.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0053",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Andressa Faria",
    email: "Andressa.Faria@ecovias.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0054",
    concession: "Econoroeste",
    area: "GEN",
    function: "Integrante",
    name: "Gabriel Acorci De Lima",
    email: "gabriel.lima@econoroeste.com.br",
    manager: "Cristiana Mara Magalhaes de Oliveira",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0055",
    concession: "Econoroeste",
    area: "GAU",
    function: "Ponto Focal",
    name: "Douglas Roberto Inacio",
    email: "douglas.inacio@econoroeste.com.br",
    manager: "Gustavo Davila",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0056",
    concession: "Econoroeste",
    area: "GAU",
    function: "Integrante",
    name: "Gustavo Scarparo Baffi",
    email: "gustavo.baffi@econoroeste.com.br",
    manager: "Gustavo Davila",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0057",
    concession: "Econoroeste",
    area: "GAU",
    function: "Integrante",
    name: "Rodrigo de Oliveira Silva",
    email: "rodrigo.silva@econoroeste.com.br",
    manager: "Gustavo Davila",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0058",
    concession: "Econoroeste",
    area: "GAU",
    function: "Integrante",
    name: "Marcelo Henrique Ferraz",
    email: "marcelo.ferraz@econoroeste.com.br",
    manager: "Gustavo Davila",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0059",
    concession: "Econoroeste",
    area: "GAU",
    function: "Integrante",
    name: "Gabriel Encarnação",
    email: "gabriel.encarnacao@ecovias.com.br",
    manager: "Gustavo Davila",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0060",
    concession: "Econoroeste",
    area: "GAU",
    function: "Integrante",
    name: "Daniele Rolim",
    email: "Daniele.Rolim@ecovias.com.br",
    manager: "Gustavo Davila",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0061",
    concession: "Econoroeste",
    area: "CSU",
    function: "Ponto Focal",
    name: "Alex Gomes Roque",
    email: "alex.roque@econoroeste.com.br",
    manager: "Nayara Marques",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0062",
    concession: "Econoroeste",
    area: "CSU",
    function: "Integrante",
    name: "Ingrid Nayara Cardoso Martins",
    email: "ingrid.martins@econoroeste.com.br",
    manager: "Nayara Marques",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0063",
    concession: "Econoroeste",
    area: "CSU",
    function: "Integrante",
    name: "Giovanna Ciasulli",
    email: "giovanna.ciasulli@econoroeste.com.br",
    manager: "Nayara Marques",
    observation: "Projetos Sociais",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0064",
    concession: "Econoroeste",
    area: "RH",
    function: "Ponto Focal",
    name: "Thafynes Lopes da Silva",
    email: "thafynes.silva@ecovias.com.br",
    manager: "Thalita Bezerra Peixoto",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0065",
    concession: "Econoroeste",
    area: "AJL",
    function: "Ponto Focal",
    name: "Barbara Salgaço Maccagnan",
    email: "barbara.maccagnan@econoroeste.com.br",
    manager: "Emily Martins Barbosa",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0066",
    concession: "Econoroeste",
    area: "AJL",
    function: "Integrante",
    name: "Felipe Pereira",
    email: "T_Felipe.Pereira@econoroeste.com.br",
    manager: "Emily Martins Barbosa",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Sociedade de Advogados Associados",
    tempoContrato: "15 meses restantes (Vence 12/2027)",
    atividadesDescricao: "Contencioso cível, notificações extrajudiciais e processos administrativos"
  },
  {
    id: "GCC0067",
    concession: "Econoroeste",
    area: "AJL",
    function: "Integrante",
    name: "Beatriz Condi",
    email: "beatriz.condi@ecorodovias.com.br",
    manager: "Emily Martins Barbosa",
    observation: "Procon",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0068",
    concession: "Econoroeste",
    area: "DAM",
    function: "Ponto Focal",
    name: "Jhonatan",
    email: "jhonatan@econoroeste.com.br",
    manager: "Fabiano Francisco Bovo",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },

  // Raposo Castello
  {
    id: "GCC0069",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Ponto Focal",
    name: "Jessica Nunes Dias Santos",
    email: "jessica.santos@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0070",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Tainara Lure Marques de Queiroz",
    email: "tainara.queiroz@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Projetus Engenharia e Consultoria",
    tempoContrato: "11 meses restantes (Vence 08/2027)",
    atividadesDescricao: "Fiscalização de contratos de ampliação de terceiras faixas"
  },
  {
    id: "GCC0071",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Maria Fernanda de Jesus Santos",
    email: "maria.santos@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Projetus Engenharia e Consultoria",
    tempoContrato: "11 meses restantes (Vence 08/2027)",
    atividadesDescricao: "Acompanhamento de cronograma físico-financeiro de obras viárias"
  },
  {
    id: "GCC0072",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Angelo Aparecido Ramos Morais",
    email: "angelo.morais@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Consórcio Pavimentação Raposo",
    tempoContrato: "7 meses restantes (Vence 04/2027)",
    atividadesDescricao: "Inspeção de usinagem asfáltica e fresagem de pavimento em campo"
  },
  {
    id: "GCC0073",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Diego Ferreira de Brito",
    email: "diego.brito@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Consórcio Pavimentação Raposo",
    tempoContrato: "7 meses restantes (Vence 04/2027)",
    atividadesDescricao: "Topografia, controle tecnológico de solos e ensaios de campo"
  },
  {
    id: "GCC0074",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Mayara Lopes de Oliveira",
    email: "mayara.oliveira@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Projetus Engenharia e Consultoria",
    tempoContrato: "16 meses restantes (Vence 01/2028)",
    atividadesDescricao: "Apoio de engenharia em licenciamento ambiental e drenagem viária"
  },
  {
    id: "GCC0075",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Carlos Eduardo Yamaoka",
    email: "carlos.yamaoka@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Consórcio Pavimentação Raposo",
    tempoContrato: "5 meses restantes (Vence 02/2027)",
    atividadesDescricao: "Supervisão de frentes de recuperação estrutural de OAEs (pontes e viadutos)"
  },
  {
    id: "GCC0076",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Lucas de Paula Assumpcao Costa",
    email: "lucas.costa@ecovias.com.br",
    manager: "Vinicius Zampieri de Lima",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Consórcio Pavimentação Raposo",
    tempoContrato: "5 meses restantes (Vence 02/2027)",
    atividadesDescricao: "Apoio no controle de segurança do trabalho e sinalização de obras"
  },
  {
    id: "GCC0077",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Vinicius Zampieri de Lima",
    email: "vinicius.lima@ecovias.com.br",
    manager: "Daniel Schenkel",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0078",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Christopher Lapuente Pinheiro",
    email: "christopher.pinheiro@ecovias.com.br",
    manager: "Daniel Schenkel",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0079",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Tierre Campos da Silva",
    email: "tierre.silva@ecovias.com.br",
    manager: "Daniel Schenkel",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0080",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Daniele Rolim",
    email: "daniele.rolim@ecovias.com.br",
    manager: "Daniel Schenkel",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0081",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Grupo de E-mail",
    name: "Correspondência GAU",
    email: "correspondenciasgau@ecovias.com.br",
    manager: "Daniel Schenkel",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0082",
    concession: "Raposo Castello",
    area: "GEN",
    function: "Integrante",
    name: "Gabriel Encarnação",
    email: "gabriel.encarnacao@ecovias.com.br",
    manager: "Vinicius A. Antonioli",
    observation: "Obras",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0083",
    concession: "Raposo Castello",
    area: "CSU",
    function: "Ponto Focal",
    name: "Natacha D Ordaz Lhano Santos",
    email: "natacha.santos@ecovias.com.br",
    manager: "Thiago de Oliveira Machado",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0084",
    concession: "Raposo Castello",
    area: "CSU",
    function: "Integrante",
    name: "Natalia Pavan Schultz",
    email: "natalia.schultz@ecovias.com.br",
    manager: "Thiago de Oliveira Machado",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0085",
    concession: "Raposo Castello",
    area: "RH",
    function: "Ponto Focal",
    name: "Beatriz Marques",
    email: "beatriz.marques@ecovias.com.br",
    manager: "Thalita Peixoto",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0086",
    concession: "Raposo Castello",
    area: "AJL",
    function: "Ponto Focal",
    name: "Gabriela Rodrigues Ferreira",
    email: "gabriela.ferreira@ecovias.com.br",
    manager: "Larissa Paganelli",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0087",
    concession: "Raposo Castello",
    area: "AJL",
    function: "Integrante",
    name: "Bruno Montanari Pereira",
    email: "bruno.pereira@ecovias.com.br",
    manager: "Larissa Paganelli",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0088",
    concession: "Raposo Castello",
    area: "AJL",
    function: "Integrante",
    name: "Rafael Luz",
    email: "Rafael.Luz@ecorodovias.com.br",
    manager: "Larissa Paganelli",
    observation: "Procon",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0089",
    concession: "Raposo Castello",
    area: "AJL",
    function: "Grupo de E-mail",
    name: "Contencioso",
    email: "Contencioso@ecorodovias.com.br",
    manager: "Larissa Paganelli",
    observation: "Procon",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0090",
    concession: "Raposo Castello",
    area: "AJL",
    function: "Integrante",
    name: "Beatriz Condi",
    email: "beatriz.condi@ecorodovias.com.br",
    manager: "Larissa Paganelli",
    observation: "Procon",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0091",
    concession: "Raposo Castello",
    area: "COM",
    function: "Ponto Focal",
    name: "Luana de Fatima Ferrari",
    email: "luana.ferrari@ecovias.com.br",
    manager: "Luana de Fatima Ferrari",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0092",
    concession: "Raposo Castello",
    area: "COM",
    function: "Integrante",
    name: "Leticia Penteado Figueiredo Holtz",
    email: "leticia.holtz@ecovias.com.br",
    manager: "Luana de Fatima Ferrari",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0093",
    concession: "Raposo Castello",
    area: "DTC",
    function: "Ponto Focal",
    name: "Monique Cruz",
    email: "monique.cruz@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "",
    status: "Ativo",
    tipoVinculo: "Próprio"
  },
  {
    id: "GCC0094",
    concession: "Raposo Castello",
    area: "DTC",
    function: "Integrante",
    name: "William Hartwig",
    email: "william.hartwig@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Telcon ITS & Telecomunicações",
    tempoContrato: "18 meses restantes (Vence 03/2028)",
    atividadesDescricao: "Manutenção de câmeras CFTV, PMVs (painéis de mensagem) e fibra óptica viária"
  },
  {
    id: "GCC0095",
    concession: "Raposo Castello",
    area: "DTC",
    function: "Integrante",
    name: "Wesley Zanella",
    email: "wesley.zanella@ecovias.com.br",
    manager: "Ricardo Gimenes",
    observation: "Prestador Homologado",
    status: "Ativo",
    tipoVinculo: "Terceiro",
    empresaTerceira: "Telcon ITS & Telecomunicações",
    tempoContrato: "18 meses restantes (Vence 03/2028)",
    atividadesDescricao: "Suporte especializado aos sistemas de pedágio eletrônico (Free Flow e semi-automático)"
  }
];
